# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together=set([('account', 'project')]),
        ),
    ]
