# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 09:49
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161228_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_photo_location),
        ),
    ]
